### ISSUE TITLE
Add `--output` flag 

### ISSUE THREAD

**Issue by stiliajohny** [homeport/termshot#30]
Hi, great work,

Have you consider adding an `--output` flag so the filename is not defaulting to `out.png`

**Comment by HeavyWombat** [comment]
@stiliajohny Thanks for the issue. I am terrible slow with responding to issues in github.com/homeport these days. So I apologise for the very late response here. It should be fixed with #24 and released in https://github.com/homeport/termshot/releases/tag/v0.2.2. The name of the flag is `--filename`. Now that I think about it, maybe `--output` would have been better.
